# Generated by Django 2.2.4 on 2019-11-01 09:43

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('photo', models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visit', models.DateField(blank=True)),
                ('manicure', models.BooleanField(default=False)),
                ('pedicure', models.BooleanField(default=False)),
                ('manicure_correction', models.BooleanField(default=False)),
                ('pedicure_correction', models.BooleanField(default=False)),
                ('pay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='first.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='image')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='first.Client')),
                ('visit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='first.Visit')),
            ],
        ),
    ]
